### PR TITLE
Filter ex aequo scores by terms length ascending

### PR DESCRIPTION
**Pull request by brunetton**
Filter same scores results by length.

Example:

```
options = [
    'car_1',
    'car_2',
    'car_3',
    'car_4',
    'car',
]
```

When searching for `ca`, all items in options have the same score. But its feels intuitive to have `car` result in first, then `car_*`

### CODE REVIEW

**Comment by bripkens** [comment]
Sounds like a good addition @brunetton! Could you please add a test case for this? Once done, I'll merge and release asap :)

**Comment by bripkens** [comment]
Taking over from here.

**Comment by bripkens** [comment]
Thanks!

**Comment by brunetton** [comment]
You're welcome !
Sorry, I didn't find time to write unit tests for now.

2016-03-07 6:35 GMT+01:00 Ben Ripkens notifications@github.com:

**Comment by brunetton** [comment]
This is probably not the good place to mention it, but for your information, I use fuzzy.js in a project here :
https://github.com/brunetton/adminer-tables_fuzzy_search

**Comment by bripkens** [comment]
I always appreciate usage information @brunetton! Nice to hear that, thank you! :)

**Pull request merged**
